Team3CAS/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Team3CAS.Controllers
{
    public class LoginController : Controller
    {
        ClinicalELDAL.Repository.UserRepository userRepo;
        public LoginController()
        {
            userRepo = new ClinicalELDAL.Repository.UserRepository();
        }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Team3CAS.Models.LoginUser uvm)
        {
            ClinicalELDAL.EntityLayer.User u = userRepo.CheckUser(uvm.UserID, uvm.Password);
            if (u == null)
            {
                Session["RoleID"] = -1;
                return View(uvm);
            }
            else
            {
                Session["UserID"] = u.UserID;
                Session["Name"] = u.Name;
                Session["RoleID"] = u.RoleID;

                if (Convert.ToInt32(Session["RoleID"]) == 1)
                {
                    return RedirectToAction("ViewPatient", "Doctor");
                }
                else if (Convert.ToInt32(Session["RoleID"]) == 2)
                {
                    return RedirectToAction("Index", "Book");
                }
                else if (Convert.ToInt32(Session["RoleID"]) == 3)
                {
                    return RedirectToAction("NewDrug", "Drug");
                }
                else if (Convert.ToInt32(Session["RoleID"]) == 4)
                {
                    return RedirectToAction("NewUser", "User");
                }
                return RedirectToAction("Index", "Anonymous");
            }

        }
        public ActionResult ViewUserType()
        {
            ViewBag.mo = TempData["RoleID"];
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Anonymous");
        }

    }
}

Team3CAS/Views/Login/Index.cshtml
@model Team3CAS.Models.LoginUser

<h2>Login to Medicare Hospital</h2>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-8 col-md-offset-2">
            @using (Html.BeginForm("Index", "Login", FormMethod.Post))
            {
                <div class="form-group">
                    <label class="control-label">UserID</label>
                    @Html.TextBoxFor(x => x.UserID, new { @class = "form-control", maxlength = "50" })
                    <div>
                        @Html.ValidationMessageFor(x => x.UserID)
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label">Password</label>
                    @Html.EditorFor(x => x.Password, new { htmlAttributes = new { @class = "form-control", maxlength = "15" } })
                    <div>
                        @Html.ValidationMessageFor(x => x.Password)
                    </div>
                </div>
                <button type="submit" class="btn btn-default" value="submit">Submit</button>
                

                <div class="form-group">

                </div>

            }
        </div>
    </div>
</div>

Team3CAS/Views/Login/ViewUserType.cshtml
@{
    ViewBag.Title = "ViewUserType";
}

@{
    string roleid = ViewBag.mo;
}