Team3CAS/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Team3CAS.Controllers
{
    public class BookController : Controller
    {
        ClinicalELDAL.Repository.PatientRepository prt;
        ClinicalELDAL.Repository.ApprovedRepository apprp;
        ClinicalELDAL.Repository.MessageRepository msgrp;

        // GET: Book
        public ActionResult Index()
        {
            prt =new ClinicalELDAL.Repository.PatientRepository();
            List<ClinicalELDAL.EntityLayer.Appointment> apoints = prt.GetAppointments();
            return View(apoints);
        }


        public ActionResult Index2()
        {
            ViewModels.BookViewModel vp = new ViewModels.BookViewModel();
            return View(vp);
        }
     

       [HttpPost]
        public ActionResult Index2(ViewModels.BookViewModel apt)
        {
            ClinicalELDAL.EntityLayer.Appointment appointment = new ClinicalELDAL.EntityLayer.Appointment();
            prt = new ClinicalELDAL.Repository.PatientRepository();
            if (ModelState.IsValid)
            {
                appointment.PatientUserID = Convert.ToInt32(Session["UserID"]);
                appointment.DoctorUserID = apt.DoctorUserID;
                appointment.Date = apt.Date;
                appointment.Status = "inactive";
                appointment.Time = apt.Time;
                bool b = prt.AddApppointment(appointment);
                if(b==true)
                {
                    return RedirectToAction("Index");
                }
                else
                return RedirectToAction("AddAppointment");
            }
            ViewModels.BookViewModel aptobj = new ViewModels.BookViewModel();
            return View(aptobj);
        }

        public ActionResult Approvedview()
        {
                
            apprp = new ClinicalELDAL.Repository.ApprovedRepository();
            List<ClinicalELDAL.EntityLayer.Appointment> apoint = apprp.GetApprovedAppointments();
            return View(apoint);
        }

        public ActionResult Messageview()
        {
            string docid = Request.QueryString["docid"];
            ViewBag.DoctorID = docid;
            ViewModels.MessageViewModel mvm = new ViewModels.MessageViewModel();
            mvm.RecieverID =Convert.ToInt32( docid);
            return View(mvm);
        }
        [HttpPost]
        public ActionResult Messageview(ViewModels.MessageViewModel msgvm)
        {
            ClinicalELDAL.EntityLayer.Message message = new ClinicalELDAL.EntityLayer.Message();
            msgrp = new ClinicalELDAL.Repository.MessageRepository();
            if(ModelState.IsValid)
            {
                message.SenderID = Convert.ToInt32(Session["UserID"]);
                message.RecieverID =msgvm.RecieverID;
                message.Body = msgvm.Body;
                message.Date = msgvm.Date;
                message.Time = msgvm.Time;
                message.Status = "unread";
                bool b = msgrp.AddMessage(message);
                if (b == true)
                {
                    return RedirectToAction("Index");
                }
                else
                    return RedirectToAction("Messageview");
            }

            ViewModels.MessageViewModel msgvmobj = new ViewModels.MessageViewModel();
            return View(msgvmobj);
        }
        public ActionResult ViewMsgTable()
        {
            msgrp = new ClinicalELDAL.Repository.MessageRepository();
            List<ClinicalELDAL.EntityLayer.Message> messages = msgrp.GetMessage(Convert.ToInt32(Session["UserID"]));
            return View(messages);
        }
    }
}

Team3CAS/Controllers/DoctorController.cs
using ClinicalELDAL.EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Team3CAS.Controllers
{
    public class DoctorController : Controller
    {
        // GET: Doctor
        ClinicalELDAL.Repository.DrugRepository DrugRepo;
        ClinicalELDAL.Repository.UserRepository UserRepo;
        public DoctorController()
        {

            DrugRepo = new ClinicalELDAL.Repository.DrugRepository();
            UserRepo = new ClinicalELDAL.Repository.UserRepository();

        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewDrug()
        {
            List<ClinicalELDAL.EntityLayer.Drug> drugs = new List<ClinicalELDAL.EntityLayer.Drug>();
            drugs = DrugRepo.GetAllDrugs();
            return View(drugs);
        }

        public ActionResult AddToCart()
        {
            List<ClinicalELDAL.EntityLayer.OrderItem> orderitem = Session["OrderItem"] as List<OrderItem>;
            ClinicalELDAL.EntityLayer.OrderItem obj = new ClinicalELDAL.EntityLayer.OrderItem();
            obj.DrugID = Convert.ToInt32(Request.Form["DrugID"]);
            obj.Quantity = Convert.ToInt32(Request.Form["quantity"]);
            orderitem.Add(obj);
            Session["OrderItem"] = orderitem;
           

            return RedirectToAction("ViewDrug");
                }

        public ActionResult ViewCart()
        {
        List<ClinicalELDAL.EntityLayer.OrderItem>     orderitem = Session["OrderItem"] as List<OrderItem>;
            // Request.Form["quantity"] = obj.Quantity.ToString();



            List<ViewModels.CartViewModel> list = new List<ViewModels.CartViewModel>();
            foreach (var item in orderitem)
            {
                ViewModels.CartViewModel cvm = new ViewModels.CartViewModel();
                var drg = DrugRepo.GetSpecificDrug(item.DrugID);
                cvm.DrugID = drg.DrugID;
                cvm.Name = drg.Name;
                cvm.Description = drg.Description;
                cvm.Quantity = item.Quantity.Value;
                cvm.Price = drg.Price.Value;
                cvm.TotalCost = drg.Price.Value * item.Quantity.Value;
                list.Add(cvm);
            }

            Session["ViewCart"] = list;
            return View(list);
        }
        public ActionResult PlaceOrder()
        {
            DrugRepo.AddOrder(Session["OrderItem"] as List<OrderItem>,Convert.ToInt32( Session["UserID"]));

            return View();
        }

        public ActionResult ViewPatient()
        {
            List<ClinicalELDAL.EntityLayer.Appointment> users = new List<ClinicalELDAL.EntityLayer.Appointment>();
            users = UserRepo.GetSpecificPatient(20);
            return View(users);
        }
    }
}

Team3CAS/Controllers/DrugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Team3CAS.Controllers
{
    public class DrugController : Controller
    {
        // GET: Drug
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewDrug()
        {
            ViewModels.DrugViewModel vm = new ViewModels.DrugViewModel();
            return View(vm);
        }
        [HttpPost]
        public ActionResult NewDrug(ViewModels.DrugViewModel dvm)
        {

            if (ModelState.IsValid)
            {
                ClinicalELDAL.Repository.DrugRepository drug = new ClinicalELDAL.Repository.DrugRepository();
                ClinicalELDAL.EntityLayer.Drug drg = new ClinicalELDAL.EntityLayer.Drug();
                drg.DrugID = dvm.DrugID;
                drg.Name = dvm.Name;
                drg.Composition = dvm.Composition;
                drg.Quantity = dvm.Quantity;
                drg.Description = dvm.Description;
                drg.Price = Convert.ToDecimal(dvm.Price);
                drug.AddDrug(drg);
                return RedirectToAction("Index");

            }

            ViewModels.DrugViewModel vm = new ViewModels.DrugViewModel();
            return View(vm);
        }
    }
}

Team3CAS/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Team3CAS.Controllers
{
    public class UserController : Controller
    {
        ClinicalELDAL.Repository.UserRepository userRepo;
        public UserController()
        {
            userRepo = new ClinicalELDAL.Repository.UserRepository();
        }
        public ActionResult Index()
        {
            List<ClinicalELDAL.EntityLayer.User> users;
            string txtSearch = Request.Form["txtSearch"];
            if (txtSearch == null)
                users = userRepo.GetAllUsers();
            //call getallusers if txtsearch is null
            //else
            //call searchusers(txtvalue)
            else
                users = userRepo.SearchUsers(txtSearch);
            return View(users);
        }

        public ActionResult NewUser()
        {
            ViewModels.UserViewModel vm = new ViewModels.UserViewModel();
            return View(vm);
        }
        [HttpPost]
        public ActionResult NewUser(ViewModels.UserViewModel uvm)
        {
            uvm.UserStatus = 1;
            if (ModelState.IsValid)
            {
                ClinicalELDAL.Repository.UserRepository user = new ClinicalELDAL.Repository.UserRepository();
                ClinicalELDAL.EntityLayer.User usr = new ClinicalELDAL.EntityLayer.User();
                usr.Name = uvm.Name;

                usr.UserID = uvm.UserID;
                usr.MedicareID = uvm.MedicareId;
                usr.Password = uvm.Password;
                usr.Name = uvm.Name;
                usr.RoleID = uvm.RoleID;
                usr.Sex = uvm.Sex;
                usr.Status = uvm.Status;
                user.AddUser(usr);
                return RedirectToAction("Index");

            }

            ViewModels.UserViewModel vm = new ViewModels.UserViewModel();
            return View(vm);
        }
        public ActionResult EditUser(string id)
        {
            ClinicalELDAL.Repository.UserRepository user = new ClinicalELDAL.Repository.UserRepository();
            ClinicalELDAL.EntityLayer.User usr = new ClinicalELDAL.EntityLayer.User();
            ViewModels.UserViewModel uvm = new ViewModels.UserViewModel();
            usr = user.GetUserByID((id));
            uvm.UserID = Convert.ToInt32(id);
            uvm.MedicareId = usr.MedicareID;
            uvm.UserID = usr.UserID;
            uvm.Password = usr.Password;
            uvm.Name = usr.Name;
            uvm.RoleID = usr.RoleID;
            uvm.Sex = usr.Sex;
            uvm.Status = usr.Status;

            return View(uvm);

        }
        [HttpPost]
        public ActionResult EditUser(ViewModels.UserViewModel uvm)
        {
            ClinicalELDAL.Repository.UserRepository user = new ClinicalELDAL.Repository.UserRepository();
            ClinicalELDAL.EntityLayer.User usr = new ClinicalELDAL.EntityLayer.User();
            usr.UserID = uvm.UserID;
            uvm.MedicareId = usr.MedicareID;
            usr.Password = uvm.Password;
            usr.Name = uvm.Name;
            uvm.RoleID = usr.RoleID;
            uvm.Sex = usr.Sex;
            uvm.Status = usr.Status;


            usr.Status = uvm.Status;
            if (user.EditUser(usr))
                return RedirectToAction("Index");
            return View(usr);
        }
    }
}

Team3CAS/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Team3CAS.Controllers
{
    public class VendorController : Controller
    {
        // GET: Vendor
        ClinicalELDAL.Repository.OrderRepository OrderRepo;
        public VendorController()
        {            
            OrderRepo = new ClinicalELDAL.Repository.OrderRepository();

        }

        public ActionResult Index()
        {
            List<ClinicalELDAL.EntityLayer.Order> orders = new List<ClinicalELDAL.EntityLayer.Order>();
            orders = OrderRepo.GetActiveOrder();
            return View(orders);
        }
        public ActionResult ViewOrder()
        {
            int orderid =Convert.ToInt32( Request.QueryString["oid"]);
            List<ClinicalELDAL.EntityLayer.OrderItem> orders = new List<ClinicalELDAL.EntityLayer.OrderItem>();
            orders = OrderRepo.GetOrderItems(orderid);
            return View(orders);
        }

        public ActionResult ApproveOrder()
        {
            int orderid = Convert.ToInt32(Request.QueryString["oid"]);           
            bool status = OrderRepo.ApproveOrder(orderid);
            return RedirectToAction("ViewOrder");
        }
    }
}

Team3CAS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="col-md-12">
        <div class="">
            <div class="page-header">
                <h1 class="text-center">Medicare Hospital</h1>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/anonymous">Medicare</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="/anonymous">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (Convert.ToInt32(Session["RoleID"]) == 0)
                {
                    <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                }
                else
                {
                <li><a href="/login/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                }

            </ul>
        </div>
    </nav>

    <div class="col-md-3" style="height:500px;padding: 10px;">
        @if (Convert.ToInt32(Session["RoleID"]) == -1)
        {
            <p>Wrong User or Password</p>
        }
        @if (Convert.ToInt32(Session["RoleID"]) == 1)
        {
            @Html.Partial("_doctor")
        }
        @if (Convert.ToInt32(Session["RoleID"]) == 2)
        {
            @Html.Partial("_patient")
        }
        @if (Convert.ToInt32(Session["RoleID"]) == 3)
        {
            @Html.Partial("_vendor")
        }
        @if (Convert.ToInt32(Session["RoleID"]) == 4)
        {
            @Html.Partial("_admin")
        }
        @if (Convert.ToInt32(Session["RoleID"]) == 0)
        {

        }
    </div>

    <div class="col-md-9" style="height:500px;padding:10px;">
        @RenderBody()

    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Team3CAS/Views/Shared/_admin.cshtml
</br>
<a href="/User/EditUser/@Session["UserID"]">Edit Profile</a>
</br>
@Html.ActionLink("Add User", "NewUser", "User")
</br>
@Html.ActionLink("View Users", "Index", "User")
</br>

Team3CAS/Views/Shared/_doctor.cshtml
</br><a href="/User/EditUser/@Session["UserID"]">Edit Profile</a></br>
@Html.ActionLink("View Drugs", "ViewDrug", "Doctor")</br>
@Html.ActionLink("View Cart", "ViewCart", "Doctor")</br>
@Html.ActionLink("View Patient", "ViewPatient", "Doctor")</br>

Team3CAS/Views/Shared/_patient.cshtml
</br>
<a href="/User/EditUser/@Session["UserID"]">Edit Profile</a></br>
@Html.ActionLink("View Appointment", "Index", "Book")
<br />
@Html.ActionLink("Book Appointment", "Index2", "Book")
<br />
@Html.ActionLink("Approved Appointment", "Approvedview", "Book")
<br />
@Html.ActionLink("Messages", "ViewMsgTable", "Book")
</br>



Team3CAS/Views/Shared/_vendor.cshtml
</br>
<a href="/User/EditUser/@Session["UserID"]">Edit Profile</a>
</br>
@Html.ActionLink("Add Drug", "NewDrug", "Drug")
<br />
@Html.ActionLink("View Order", "Index", "Vendor")
<br />
@Html.ActionLink("Approve Order", "ApproveOrder", "Vendor")
<br />